### ISSUE TITLE
The transparency of the problem window makes it unreadable

### ISSUE THREAD

**Issue by Dartt0n** [slymax/zedokai#1]
Firstly, thank you for adopting these themes for Zed. I really appreciate them. However, I have noticed a small problem that occurs with each theme.

The issue occurs when the user hovers over a detected problem in the code. A window appears that describes the error, but this window is transparent and extremely difficult to read.

<img width="864" alt="image" src="https://github.com/slymax/zedokai/assets/62600293/e292aa09-40b2-496b-a34b-037bb301e002">
I believe that could be fixed by changing the following values in each theme:

- [error.background](https://github.com/slymax/zedokai/blob/903457c55c1e95bc78e09d167846d4e2db3b0389/themes/zedokai.json#L70)
- [info.background](https://github.com/slymax/zedokai/blob/903457c55c1e95bc78e09d167846d4e2db3b0389/themes/zedokai.json#L77)
- [warning.background](https://github.com/slymax/zedokai/blob/903457c55c1e95bc78e09d167846d4e2db3b0389/themes/zedokai.json#L81)

**Comment by slymax** [comment]
thanks @Dartt0n! should be fixed in the next release
